# Generated by Django 5.2.6 on 2025-10-14 07:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Starting point address or coordinates', max_length=500)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_location', models.CharField(help_text='Pickup location address', max_length=500)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_location', models.CharField(help_text='Dropoff location address', max_length=500)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, help_text='Hours already used in current 8-day cycle (max 70)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance in miles', max_digits=10, null=True)),
                ('estimated_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration in hours', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('FUEL', 'Fuel Stop'), ('REST', 'Rest Break (30 min)'), ('SLEEPER', 'Sleeper Berth (8-10 hours)'), ('OFF_DUTY', 'Off Duty (10 hours)'), ('PICKUP', 'Pickup Stop'), ('DROPOFF', 'Dropoff Stop')], max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration of stop in minutes')),
                ('sequence_order', models.IntegerField(help_text='Order of stop in route')),
                ('distance_from_start', models.DecimalField(decimal_places=2, help_text='Miles from trip start', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sequence_order', models.IntegerField()),
                ('distance_from_start', models.DecimalField(decimal_places=2, help_text='Miles from trip start', max_digits=10)),
                ('time_from_start', models.DecimalField(decimal_places=2, help_text='Hours from trip start', max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_duty_not_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_hours', models.DecimalField(decimal_places=2, default=24, max_digits=5)),
                ('total_miles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('starting_odometer', models.IntegerField(default=0)),
                ('ending_odometer', models.IntegerField(default=0)),
                ('starting_location', models.CharField(blank=True, max_length=500)),
                ('ending_location', models.CharField(blank=True, max_length=500)),
                ('remarks', models.TextField(blank=True)),
                ('has_violation', models.BooleanField(default=False)),
                ('violation_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='core.trip')),
            ],
            options={
                'ordering': ['trip', 'log_date'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_odometer', models.IntegerField(blank=True, null=True)),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sequence_order', models.IntegerField()),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.dailylog')),
            ],
            options={
                'ordering': ['daily_log', 'start_time'],
                'indexes': [models.Index(fields=['daily_log', 'start_time'], name='core_logent_daily_l_f6448f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-created_at'], name='core_trip_created_477ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'status'], name='core_trip_user_id_bb1497_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['trip', 'sequence_order'], name='core_stop_trip_id_690cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='routewaypoint',
            index=models.Index(fields=['trip', 'sequence_order'], name='core_routew_trip_id_233690_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['trip', 'log_date'], name='core_dailyl_trip_id_f7e1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['driver', 'log_date'], name='core_dailyl_driver__cf7f9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'driver', 'log_date')},
        ),
    ]
